name: Apollo plugin checks

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: '.node-version'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint
      - run: yarn prettier --check .
      - run: yarn test
