name: NPM Publish Package

on:
  push
  # release:
  #   types: [created]

jobs:
  test:
    name: Test before publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: '.node-version'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
