name: NPM Publish Package

on:
  release:
    types: [created]

jobs:
  test:
    name: Test before publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: '.node-version'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
